# These are supported funding model platforms

github: # Si vous avez GitHub Sponsors activé
patreon: raefgaied # Si vous avez un compte Patreon
open_collective: # Si vous utilisez Open Collective
ko_fi: raefgaied # Si vous avez un compte Ko-fi
tidelift: # Pour les packages npm/PyPI
community_bridge: # Pour les projets open source
liberapay: raefgaied # Alternative européenne
issuehunt: # Pour les bounties de bugs
otechie: # Pour le support technique payant
custom: ['https://www.buymeacoffee.com/raefgaied'] # URLs personnalisées
