name: Latest blog post workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Update blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "5"
          feed_list: "https://medium.com/feed/@raef.gaied"
          comment_tag_name: "BLOG-POST-LIST"  # Corrigé pour correspondre au README
