name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"  # Runs daily at 1 AM UTC

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Update Quote
        uses: ApoorvTyagi/quote-readme@main
        with:
          OPTION: both
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
