name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '05 0 * * *'  # Runs at 00:05 UTC every day

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ajout des permissions nécessaires
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Ajout de l'étape de checkout
        
      - name: Update Waka stats
        uses: anmol098/waka-readme-stats@master  # Action plus maintenue et recommandée
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilisation du token par défaut
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "False" 
          SHOW_LANGUAGE: "False"
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
